### ISSUE TITLE
[SK/CZ] - Pouzitelnost len CRUD

### ISSUE THREAD

**Issue by FilipLukac** [iPublikuj/doctrine-crud#1]
Ahojte,

je mozne pouzit len CRUD ? pretoze pouzivam Doctrine od Kdybyho, hodilo by sa vediet pouzit iba CRUD component s jeho doctrine.

**Comment by akadlec** [comment]
Tohle není samotné Doctrine rožíšíření, tohle je právě nádstavba pro Kdyby\Doctrine, takže abys tuto ext mohl využívat potřebuješ doctrine :D

**Comment by FilipLukac** [comment]
@akadlec - super :) dakujem
